language: java

jdk:
- oraclejdk8

services:
- mysql
- docker

before_install:
- cd docker
- sudo docker-compose --version

script:
- cd ..
- chmod +x docker-compose.yml
- sudo docker-compose up -d --build
- docker ps
- chmod +x smoketest.sh
- ./smoketest.sh
