language: java

jdk:
- oraclejdk8

services:
- mysql
- docker

before_install:
- sudo rm /usr/local/bin/docker-compose
- sudo curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
- sudo chmod +x usr/local/bin/docker-compose
- docker-compose --version

script:
- chmod +x docker-compose.yml
- docker-compose up -d --build
