version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Web

    depends_on:
      - db

    ports:
      - "80:8080"
   
    links:
      - db

    environment:
        DATABASE_HOST: db
        DATABASE_USER: root
        DATABASE_PASSWORD: root
        DATABASE_NAME: dareondb
        DATABASE_PORT: 3306

    command: ["./wait-for-it.sh","db:3306","java","-Dspring.profiles.active=production","-jar","/Dareon.jar"]


  db:
    build: 
      context: .
      dockerfile: MySQL
    
    image: mysql
   
    environment:

       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: dareondb
      
        
    command: ["mysqld"]
   
    
    
 
